# Generated by Django 3.2 on 2023-04-22 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
